export const SUPABASE_URL = "https://ysrzfksvrzmqhmmtfrdu.supabase.co";
export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzcnpma3N2cnptcWhtbXRmcmR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyMjkzMzYsImV4cCI6MjA5NzgwNTMzNn0.q26VnkgYpvQfgeEVdfGLmsfJIQfHRKy4WALtFADJtnc";
